/* This library contains the implementation of function and structures used commonly by all implementations of the bat algorithms */

#ifndef __TOOLS_H__
#define __TOOLS_H__

//default values for initial parameters used by the bat algorithms
#define DEFAULT_POS         0      
#define DEFAULT_FMIN        0
#define DEFAULT_FMAX        100
#define DEFAULT_PULSE       0.2
#define DEFAULT_LOUDNESS    1.5
#define DEFAULT_GAMMA       0.9
#define DEFAULT_ALPHA       0.9

//default values for bat spawning and iterations 
#define DEFAULT_POS_RADIUS   30
#define DEFAULT_BATS_NUMBER  100
#define DEFAULT_ITERATIONS   1000

#include <stdlib.h>
#include <data.h>

/*  batAlgorithmParamters is a structure containing the initial parameters and the launch settings for the bat algorithms:
 *  initPos         ->      Initial reference position for spawning bats (the algorithm will geenrate bats around this position)
 *  initPosRadius   ->      Geenratio radius for spawning the bats
 *  [fMin,fMax]     ->      Boundaries for the geenration of freuencies used by the bats 
 *  initPulse       ->      Initial pulse of the bats
 *  initLoudness    ->      Initial loudness of the bats
 *  vectorDim       ->      Optimization problem dimension
 *  bats            ->      Number of bat to spawn 
 *  iterations      ->      Number of iterations
 */ 

typedef struct batAlgorithmParameters {
    Vector* initPos;
    double fMin;
    double fMax;
    double initPulse;
    double initLoudness;
    
    double gamma;
    double alpha;

    unsigned int vectorDim;
    double initPosRadius;
    
    unsigned int bats;
    unsigned int iterations;

} batAlgorithmParameters;

/* batAlgorithmResults is a structure generated by the bat algorithms for containing the results:
 * bestFitness ->   best fitness value obtained
 * bestPos     ->   best position obtained 
 * bestIndex   ->   index of the bat that obtained the best results
 */

typedef struct batAlgorithmResults {
    double bestFitness;
    Vector* bestPos;
    unsigned int bestIndex;
} batAlgorithmResults;

/* initParameters() allocates a batAlgorithmParameters structure and initializes all values with their defaults:
 *  parameters ->   the address of a batAlgorthmParameters structure that points to NULL
 *  vectorDim  ->   dimension of the problem 
 */
void initParameters(batAlgorithmParameters** parameters, unsigned int vectorDim);

/* destroyPArameters() destroy a batAlgorithmParameters structure:
 *  parameters ->   the address of a batAlgorthmDtructure to destroy
 */
void destroyParameters(batAlgorithmParameters** parameters);

/* printParameters() prints the content of the batAlgorithmParameters structure:
 * parameters   -> pointer of the structure to print
*/
void printParameters(batAlgorithmParameters* parameters);

/* initResultStructure() allocates a batAlgorithmResults structure:
 * results   ->     the address of a batAlgorithmResults structure that points to NULL
 * vectorDim ->     the dimension of the problem
 */
void initResults(batAlgorithmResults** results, unsigned int vectorDim);

/* destroyResultStructure() destroys a batAlgorithmResults structure:
 * results  ->  the address of a batAlgorithmResults structure
 */
void destroyResults(batAlgorithmResults** results);

/* printResults() prints the content of the batAlgorithmParameters structure:
 * results   -> pointer of the structure to print
*/
void printResults(batAlgorithmResults* results);



#endif
