/* Parallel MPI Version of the BAT Algorithm v1.0 */
// This current version only minimizes the function

#include <stdio.h>
#include <stdlib.h>

#include "data.h"
#include "bat.h"

// -- Bat Properties --
#define N_BATS 20 
#define MAX_IT 10   // Max Optimization Iterations
#define F_MIN 0
#define F_MAX 100
#define A_0 1.0     // Initial Loudness
#define R_0 0.0     // Initial Pulse Rate
#define ALPHA 0.9   // Loudness Cooling Factor
#define GAMMA 0.9   // Pulse Rate Warming Factor
#define V_BOUND 10  // Max Initial Random Velocity

// -- Function Properties --
// space is gonna be from [-X_BOUND, X_BOUND] x [-Y_BOUND, Y_BOUND]
#define X_BOUND 1000  // Max X coordinate 
#define Y_BOUND 1000  // Max Y coordinate
#define DIM 2         // Problem Dimension

int main(int argc, char** argv) {
   
    // Required data structures
    Bat ** bat_array = malloc(N_BATS * sizeof(Bat));
    // Create N Bats instances, each with random initial position and velocity
    int i;
    for (i = 0; i < N_BATS; i++) {
        batRandom(bat_array[i], X_BOUND, Y_BOUND, V_BOUND); // spawn bats with random position and velocity
    } 

    // Set system properties like min frequency, max frequency, initial loudness, and pulse emission rate

    // Evaluate initial global fitness, position with first best fitness is recorded

    // Perform Tmax iteration of the optimization loop


    // Phase A: Exploration 
    // 1 - Each bat updates frequency, velocity and position
    // Phase B: Exploitation
    // 1 - a random number is generated, if rand > pulserate_i then the bat performs
    //     a local random walk
    // 1a - a new candidate solution is generated by moving a small distance around the current best solution
    // Phase C: Acceptance
    // 1 - the new position from Global search or Local search is evaluated through random values
    // 2 - Acoustic parameters update
    // 3 - Update global best

    return 0;
}